# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту shakasuone@gmail.com если сборка упала
notifications:
  email:
    recipients:
      shakasuone@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
#
env:
  global:
    - CODECOV_TOKEN="803639b5-6f45-42fd-83d5-ab401930767c"